# MD033/no-inline-html - Inline HTML
MD033: false

# MD047/single-trailing-newline - Files should end with a single newline character
MD047: false

# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012:
  # Consecutive blank lines
  maximum: 1

# MD028/no-blanks-blockquote - Blank line inside blockquote
MD028: false

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026: false

# MD029/ol-prefix - Ordered list item prefix
MD029: false

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 100
  # Include tables
  tables: false